# volumes:
volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true

services:
  fastapi:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./sample_service:/app
  postgres:
    image: postgres:14.2-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=munch
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=munch
    ports:
      - 15432:5432

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: munch@munch.com
      PGADMIN_DEFAULT_PASSWORD: munchbunch
      PGADMIN_DISABLE_POSTFIX: 1

  munch:
    build:
      context: ./munch
      dockerfile: ./Dockerfile.dev
    ports:
      - "8010:8000"
    volumes:
      - ./munch:/app
    environment:
      DATABASE_URL: postgresql://munch:password@postgres/munch
      WAIT_HOSTS: postgres:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_MUNCH_API_HOST: http://localhost:8010
